name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - "backend/**"

jobs:
  deploy:
    name: Build and Deploy to Azure
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Log in to Azure Container Registry
        run: |
          az acr login --name ${{ secrets.ACR_LOGIN_SERVER }}

      - name: Detect Changed Files
        id: filter-changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'

      # FRONTEND - Build, Push, Deploy
      - name: Build and Push Frontend Docker Image
        if: steps.filter-changes.outputs.frontend == 'true'
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest ./frontend > /dev/null 2>&1
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest > /dev/null 2>&1

      - name: Deploy Frontend to Azure Container Apps
        if: steps.filter-changes.outputs.frontend == 'true'
        run: |
          az containerapp update \
            --name ${{ secrets.FRONTEND_APP_NAME }} \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --image ${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest > /dev/null 2>&1

      # BACKEND - Build, Push, Deploy
      - name: Build and Push Backend Docker Image
        if: steps.filter-changes.outputs.backend == 'true'
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/backend:latest ./backend > /dev/null 2>&1
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/backend:latest > /dev/null 2>&1

      - name: Deploy Backend to Azure Container Apps
        if: steps.filter-changes.outputs.backend == 'true'
        run: |
          az containerapp update \
            --name ${{ secrets.BACKEND_APP_NAME }} \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --image ${{ secrets.ACR_LOGIN_SERVER }}/backend:latest > /dev/null 2>&1
